"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type View = "campaign" | "brief" | "clips" | "revenue";
type Candidate = { id: number; title: string; hook: string; transcript: string; duration: string; score: number; predicted: string; payout: string; retention: number; risk: "Ready" | "Review"; accent: string };

const candidates: Candidate[] = [
  { id: 1, title: "The $0-to-$10K truth", hook: "I wasted 2 years building the wrong way.", transcript: "Everyone thinks the breakthrough was the product. It wasn't. The breakthrough was learning how to distribute before I built...", duration: "00:34", score: 96, predicted: "48K–92K", payout: "$144–$276", retention: 78, risk: "Ready", accent: "lime" },
  { id: 2, title: "Build distribution first", hook: "Your first 1,000 users are already somewhere.", transcript: "You don't need another feature. Find the room where your customer already spends attention, then earn the right to redirect it...", duration: "00:29", score: 91, predicted: "31K–64K", payout: "$93–$192", retention: 72, risk: "Ready", accent: "violet" },
  { id: 3, title: "The founder bottleneck", hook: "Most founders don't have a growth problem.", transcript: "If every decision still has to go through you, growth only makes the bottleneck more expensive. The answer is a repeatable system...", duration: "00:42", score: 84, predicted: "22K–45K", payout: "$66–$135", retention: 66, risk: "Review", accent: "orange" },
];

const navItems: { id: View; label: string; glyph: string }[] = [
  { id: "campaign", label: "Campaign desk", glyph: "⌁" }, { id: "brief", label: "Brief compiler", glyph: "◎" }, { id: "clips", label: "Clip lab", glyph: "✦" }, { id: "revenue", label: "Revenue plan", glyph: "↗" },
];
const hardRules = [["Duration", "25–45 seconds"], ["Platforms", "TikTok + Instagram Reels"], ["Required", "Animated captions · @AmbroHQ · #buildinpublic"], ["Avoid", "Income guarantees · profanity · competitor logos"]];
const checks = [["Length is inside 25–45s", "pass"], ["Creator handle appears on screen", "pass"], ["Required hashtag in post copy", "pass"], ["No income or outcome guarantee", "pass"], ["Original pacing and caption treatment", "pass"], ["Source rights require final confirmation", "warn"]];

export default function Home() {
  const [view, setView] = useState<View>("campaign");
  const [campaignUrl, setCampaignUrl] = useState("https://whop.com/discover/ambro-founder-clips");
  const [compiled, setCompiled] = useState(true);
  const [selectedId, setSelectedId] = useState(1);
  const [sourceName, setSourceName] = useState("Ambro founder interview — Episode 12.mp4");
  const [toast, setToast] = useState("");
  const [playing, setPlaying] = useState(false);
  const [captionStyle, setCaptionStyle] = useState<"Punch" | "Clean" | "Karaoke">("Punch");

  useEffect(() => { const saved = window.localStorage.getItem("clipwire-workspace"); if (!saved) return; try { const next = JSON.parse(saved); if (next.campaignUrl) setCampaignUrl(next.campaignUrl); if (next.selectedId) setSelectedId(next.selectedId); } catch {} }, []);
  useEffect(() => { window.localStorage.setItem("clipwire-workspace", JSON.stringify({ campaignUrl, selectedId })); }, [campaignUrl, selectedId]);
  const selected = useMemo(() => candidates.find((item) => item.id === selectedId) ?? candidates[0], [selectedId]);
  function flash(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2600); }
  function compileBrief() { setCompiled(false); window.setTimeout(() => { setCompiled(true); setView("brief"); flash("Campaign rules compiled into a clip brief"); }, 650); }
  function loadSource(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) { setSourceName(file.name); flash("Source added — ready for transcript analysis"); } }

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand-row"><div className="brand-mark">CW</div><div><strong>CLIPWIRE</strong><span>Campaign intelligence</span></div></div>
      <nav className="main-nav" aria-label="Workspace navigation"><p className="eyebrow">Workspace</p>{navItems.map((item) => <button key={item.id} className={view === item.id ? "nav-button active" : "nav-button"} onClick={() => setView(item.id)}><span>{item.glyph}</span>{item.label}</button>)}</nav>
      <div className="campaign-list"><div className="list-head"><p className="eyebrow">Campaigns</p><button aria-label="Add campaign" onClick={() => setView("campaign")}>+</button></div>
        <button className="campaign-row selected" onClick={() => setView("campaign")}><span className="mini-logo coral">A</span><span><strong>Ambro Founder Clips</strong><small>$3.00 / 1K views</small></span></button>
        <button className="campaign-row" onClick={() => flash("Demo campaign selected")}><span className="mini-logo blue">S</span><span><strong>SaaS Growth Cuts</strong><small>$1.50 / 1K views</small></span></button>
        <button className="campaign-row" onClick={() => flash("Demo campaign selected")}><span className="mini-logo gold">V</span><span><strong>Viral Founder</strong><small>$5.00 / 1K views</small></span></button>
      </div>
      <div className="goal-card"><div className="goal-ring"><span>$1.8K</span><small>this month</small></div><div><p>Path to $10K</p><strong>18% funded</strong><button onClick={() => setView("revenue")}>Open revenue plan →</button></div></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div className="crumbs"><span>Campaigns</span><b>/</b><strong>Ambro Founder Clips</strong></div><div className="top-actions"><span className="live-pill"><i /> Campaign active</span><button className="icon-button" aria-label="Notifications" onClick={() => flash("No new campaign alerts")}>◌</button><button className="avatar" aria-label="Account menu" onClick={() => flash("Workspace owner")}>SS</button></div></header>
      <div className="content">
        {view === "campaign" && <CampaignDesk campaignUrl={campaignUrl} setCampaignUrl={setCampaignUrl} compileBrief={compileBrief} compiled={compiled} setView={setView} sourceName={sourceName} loadSource={loadSource} flash={flash} />}
        {view === "brief" && <BriefCompiler setView={setView} flash={flash} />}
        {view === "clips" && <ClipLab selected={selected} setSelectedId={setSelectedId} playing={playing} setPlaying={setPlaying} captionStyle={captionStyle} setCaptionStyle={setCaptionStyle} flash={flash} />}
        {view === "revenue" && <RevenuePlan setView={setView} />}
      </div>
    </section>
    {toast && <div className="toast" role="status">✓ {toast}</div>}
  </main>;
}

function CampaignDesk({ campaignUrl, setCampaignUrl, compileBrief, compiled, setView, sourceName, loadSource, flash }: { campaignUrl: string; setCampaignUrl: (value: string) => void; compileBrief: () => void; compiled: boolean; setView: (view: View) => void; sourceName: string; loadSource: (event: ChangeEvent<HTMLInputElement>) => void; flash: (message: string) => void }) {
  return <>
    <section className="hero-grid"><div className="hero-copy"><span className="section-kicker">Campaign command center</span><h1>Turn a campaign brief into clips built to <em>win.</em></h1><p>Clipwire converts payout rules, creative preferences, and source footage into ranked, compliant edits—before you spend time exporting.</p></div>
      <div className="economics-card"><span>Campaign economics</span><strong>$3.00 <small>/ 1K views</small></strong><div className="budget-line"><span><b>$2,180</b> remaining</span><span>73%</span></div><div className="progress"><i /></div><small>Cap: $3,000 · Ends in 18 days</small></div></section>
    <section className="stepper" aria-label="Campaign workflow">{[["1","Import","Campaign rules"],["2","Compile","Structured brief"],["3","Analyze","Source footage"],["4","Review","Ranked clips"]].map((step,index) => <div className={index < 2 ? "step done" : index === 2 ? "step current" : "step"} key={step[0]}><span>{index < 2 ? "✓" : step[0]}</span><p><strong>{step[1]}</strong><small>{step[2]}</small></p></div>)}</section>
    <div className="desk-grid">
      <section className="panel import-panel"><div className="panel-head"><div><span className="section-kicker">01 · Import</span><h2>Campaign source</h2></div><span className="whop-badge">W Whop</span></div><label htmlFor="campaign-url">Campaign link or requirements</label><div className="input-action"><input id="campaign-url" value={campaignUrl} onChange={(event) => setCampaignUrl(event.target.value)} /><button className="primary-button" onClick={compileBrief}>{compiled ? "Recompile brief" : "Reading campaign…"}</button></div><p className="helper">Paste a public campaign link, or replace it with the campaign rules. Clipwire separates must-follow rules from creative guidance.</p><div className="import-result"><div className="mini-logo coral">A</div><div><strong>Ambro Founder Clips</strong><span>Imported from Whop · refreshed just now</span></div><span className="match-pill">12 rules found</span></div></section>
      <section className="panel source-panel"><div className="panel-head"><div><span className="section-kicker">02 · Source</span><h2>Footage library</h2></div><span className="small-status">1 source</span></div><div className="source-file"><div className="source-thumb"><span>▶</span><small>38:14</small></div><div><strong>{sourceName}</strong><span>Transcript ready · 14 high-signal moments</span><div className="signal-line"><i /><i /><i /><i /><i /></div></div><label className="replace-button">Replace<input type="file" accept="video/*,audio/*" onChange={loadSource} /></label></div><button className="ghost-button full" onClick={() => flash("Add another source using the Replace control in this prototype")}>＋ Add YouTube link or source file</button></section>
    </div>
    <section className="panel brief-preview"><div className="panel-head"><div><span className="section-kicker">Compiled campaign brief</span><h2>The rules your clip must satisfy</h2></div><button className="text-button" onClick={() => setView("brief")}>Edit structured brief →</button></div><div className="rules-grid">{hardRules.map(([label,value],index) => <div className="rule" key={label}><span className={index === 3 ? "rule-icon danger" : "rule-icon"}>{index === 3 ? "!" : "✓"}</span><div><small>{label}</small><strong>{value}</strong></div></div>)}</div><div className="creative-row"><span>Creative target</span><strong>Fast founder insight</strong><i /><strong>Pattern interrupt in 1.5s</strong><i /><strong>High-contrast captions</strong><i /><strong>Clear standalone takeaway</strong></div><button className="launch-button" onClick={() => setView("clips")}><span>✦</span><div><strong>Generate ranked clip concepts</strong><small>Find the best moments for this exact campaign</small></div><b>→</b></button></section>
  </>;
}

function BriefCompiler({ setView, flash }: { setView: (view: View) => void; flash: (message: string) => void }) {
  const [weights, setWeights] = useState({ compliance: 50, retention: 30, payout: 20 });
  return <><PageTitle kicker="Brief compiler" title="Make the campaign machine-readable." copy="Review what the campaign requires, what it prefers, and how Clipwire should rank opportunities." /><div className="brief-layout"><section className="panel rule-editor"><div className="panel-head"><div><span className="section-kicker">Hard constraints</span><h2>Submission gate</h2></div><span className="match-pill">4 groups · required</span></div>{hardRules.map(([label,value],index) => <label className="editor-row" key={label}><span>{index+1}</span><div><small>{label}</small><input defaultValue={value} /></div><button onClick={() => flash(`${label} rule kept`)}>Keep</button></label>)}</section><aside className="side-stack"><section className="panel"><span className="section-kicker">Ranking weights</span><h2>What should win?</h2>{(Object.keys(weights) as (keyof typeof weights)[]).map((key) => <label className="range-row" key={key}><span><b>{key}</b><strong>{weights[key]}%</strong></span><input type="range" min="0" max="100" value={weights[key]} onChange={(event) => setWeights({...weights,[key]:Number(event.target.value)})} /></label>)}</section><section className="panel guardrail-card"><span className="section-kicker">Safety rail</span><h2>Never auto-submit</h2><p>Final source-rights confirmation and account posting remain human decisions.</p><span className="safe-pill">Human approval required</span></section><button className="launch-button compact" onClick={() => setView("clips")}><span>✦</span><div><strong>Apply brief and rank clips</strong><small>Use the current scoring mix</small></div><b>→</b></button></aside></div></>;
}

function ClipLab({ selected, setSelectedId, playing, setPlaying, captionStyle, setCaptionStyle, flash }: { selected: Candidate; setSelectedId: (id: number) => void; playing: boolean; setPlaying: (value: boolean) => void; captionStyle: "Punch" | "Clean" | "Karaoke"; setCaptionStyle: (value: "Punch" | "Clean" | "Karaoke") => void; flash: (message: string) => void }) {
  return <><PageTitle kicker="Clip lab" title="Three moments worth editing." copy="Candidates are ranked against Ambro's rules—not generic virality advice." action={<button className="primary-button" onClick={() => flash("Source scan refreshed · rankings unchanged")}>↻ Re-analyze source</button>} /><div className="lab-layout">
    <section className="candidate-column"><div className="candidate-head"><span>Ranked candidates</span><small>Fit score combines compliance + retention + payout</small></div>{candidates.map((candidate,index) => <button className={selected.id === candidate.id ? "candidate-card selected" : "candidate-card"} key={candidate.id} onClick={() => { setSelectedId(candidate.id); setPlaying(false); }}><span className="rank">0{index+1}</span><div className={`candidate-visual ${candidate.accent}`}><span>{candidate.duration}</span><i>{candidate.retention}% retention</i></div><div className="candidate-copy"><div><span className={candidate.risk === "Ready" ? "ready-tag" : "review-tag"}>{candidate.risk}</span><strong>{candidate.title}</strong></div><p>“{candidate.hook}”</p><small>{candidate.transcript}</small><div className="metric-row"><span>Views <b>{candidate.predicted}</b></span><span>Est. payout <b>{candidate.payout}</b></span></div></div><div className="fit-score"><strong>{candidate.score}</strong><small>fit</small></div></button>)}</section>
    <section className="preview-column"><div className="phone-wrap"><div className={`phone-screen ${selected.accent}`}><div className="phone-top"><span>AMBRO</span><b>● ● ●</b></div><div className="portrait-shape"><i /><span /></div><div className={`caption caption-${captionStyle.toLowerCase()}`}>I WASTED <em>2 YEARS</em><br />BUILDING THE WRONG WAY.</div><button className="play-button" aria-label={playing ? "Pause preview" : "Play preview"} onClick={() => setPlaying(!playing)}>{playing ? "Ⅱ" : "▶"}</button><div className="phone-lower"><span>@AmbroHQ</span><p>The distribution lesson every founder learns too late.</p><b>#buildinpublic</b></div><div className="phone-progress"><i className={playing ? "playing" : ""} /></div></div></div><div className="style-tabs" aria-label="Caption style">{(["Punch","Clean","Karaoke"] as const).map((style) => <button className={captionStyle === style ? "active" : ""} onClick={() => setCaptionStyle(style)} key={style}>{style}</button>)}</div><div className="timeline"><div className="timeline-time"><span>00:00</span><span>{selected.duration}</span></div><div className="audio-wave">{Array.from({length:34}).map((_,index) => <i key={index} style={{height:`${8+((index*13)%26)}px`}} />)}</div></div></section>
    <aside className="compliance-column"><div className="compliance-score"><div className="score-orbit"><strong>{selected.score}</strong><small>/100</small></div><div><span>Campaign fit</span><strong>{selected.risk === "Ready" ? "Ready to review" : "1 item to review"}</strong></div></div><section className="panel compliance-panel"><div className="panel-head"><div><span className="section-kicker">Submission gate</span><h2>Compliance check</h2></div></div>{checks.map(([label,status]) => <div className="check-row" key={label}><span className={status === "pass" ? "check pass" : "check warn"}>{status === "pass" ? "✓" : "!"}</span><p>{label}</p></div>)}</section><section className="payout-box"><span>Expected campaign payout</span><strong>{selected.payout}</strong><small>Based on predicted qualified views at $3 RPM</small></section><button className="export-button" onClick={() => flash("Clip package marked ready for human export review")}>Mark ready for export <span>↗</span></button><p className="fine-print">Prototype mode: creates an export plan. Rendering and direct posting come in the next build.</p></aside>
  </div></>;
}

function RevenuePlan({ setView }: { setView: (view: View) => void }) {
  return <><PageTitle kicker="Revenue plan" title="Make $10K a portfolio problem." copy="Track the number of qualified views, clips, and campaigns needed—then work the highest-return queue first." action={<button className="primary-button" onClick={() => setView("clips")}>Open next clip →</button>} /><div className="revenue-stats">{[["Monthly target","$10,000","Goal"],["Projected","$7,420","+18% vs last month"],["Qualified views needed","2.86M","blended $3.50 RPM"],["Clips to publish","96","24 per week"]].map(([label,value,note]) => <div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="revenue-layout"><section className="panel projection-panel"><div className="panel-head"><div><span className="section-kicker">Monthly projection</span><h2>Revenue by campaign</h2></div><span className="match-pill">74% of target</span></div><div className="bar-chart">{[["Ambro",74,"$3,420"],["SaaS Growth",48,"$2,180"],["Viral Founder",31,"$1,420"],["Affiliate funnel",14,"$400"]].map(([name,size,value]) => <div className="bar-row" key={name}><span>{name}</span><div><i style={{width:`${size}%`}} /></div><strong>{value}</strong></div>)}</div></section><section className="panel sprint-panel"><span className="section-kicker">This week's sprint</span><h2>Highest-leverage queue</h2>{[["Publish Ambro candidate #1","$144–$276"],["Create 3 hook variants","+22% upside"],["Import one $5+ RPM campaign","Portfolio gap"],["Review 7-day retention","Friday"]].map(([task,value],index) => <div className="sprint-row" key={task}><span>{index+1}</span><p><strong>{task}</strong><small>{value}</small></p><i>{index === 0 ? "Now" : ""}</i></div>)}</section></div><section className="panel model-note"><div><span className="section-kicker">Operating thesis</span><h2>Don't chase views. Chase qualified value per edit hour.</h2></div><p>Clipwire prioritizes campaigns with healthy remaining budgets, achievable creative fit, clear rights, and payout upside. Native platform revenue is treated as a bonus—not the business model.</p></section></>;
}

function PageTitle({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: React.ReactNode }) { return <header className="page-title"><div><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{copy}</p></div>{action}</header>; }
